# Generated by Django 5.1.6 on 2025-03-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(null=True, verbose_name='Telegram ID')),
                ('account', models.CharField(max_length=5000, null=True, verbose_name='Phone')),
                ('sb_id', models.CharField(max_length=5000, null=True, verbose_name='SB ID')),
                ('sum', models.IntegerField(null=True, verbose_name='Сумма')),
                ('name', models.CharField(max_length=5000, null=True, verbose_name='Имя для Тильды')),
                ('payment_title', models.CharField(max_length=5000, null=True, verbose_name='Назначение платежа')),
                ('phone', models.CharField(max_length=5000, null=True, verbose_name='Номер для тильды')),
                ('email', models.CharField(max_length=5000, null=True, verbose_name='Email для тильды')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(verbose_name='Telegram ID')),
                ('name', models.CharField(max_length=5000, null=True)),
                ('amount', models.IntegerField(null=True, verbose_name='Кол-во приглашенных')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(max_length=18, unique=True)),
                ('prv_txn', models.CharField(blank=True, max_length=20, null=True)),
                ('account', models.CharField(max_length=200)),
                ('command', models.CharField(max_length=10)),
                ('txn_date', models.DateTimeField(blank=True, null=True)),
                ('sum', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('result', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('telegram_id', models.BigIntegerField(help_text='Telegram ID', verbose_name='Telegram ID')),
                ('send', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
