# Generated by Django 5.1.6 on 2025-03-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='kaspi_order_id',
            field=models.CharField(max_length=5000, null=True, verbose_name='ID заказа для Каспи'),
        ),
    ]
