version = 4.2.0
archive_dir = /etc/letsencrypt/archive/api.finance-assel.kz
cert = /etc/letsencrypt/live/api.finance-assel.kz/cert.pem
privkey = /etc/letsencrypt/live/api.finance-assel.kz/privkey.pem
chain = /etc/letsencrypt/live/api.finance-assel.kz/chain.pem
fullchain = /etc/letsencrypt/live/api.finance-assel.kz/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 13a9d00cc2810bf71f79f2188ab8a427
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
api.finance-assel.kz = /var/www/certbot
